/**
 * List of black cards, each line must be into " " and finish by ','.
 *
 * @author GIRARD Timothée
 * @version 1.0
 */

/**
 * 108 black cards.
 *
 * @type {string[]} the tab of black cards.
 */
const BLACK_CARDS_LIST = [
"Lorsque j'étais _, j'étais vraiment le plus heureux au monde !",
"J'aime mettre mon pénis _.",
"_ #OKLM",
"Pour couronner le tout, _ serait parfait !",
"Le meilleur de _, c'est sans _ !",
"_ #qui ne tente rien n'a rien x)",
"Il était une fois, _ et _ vécurent heureux et eurent beaucoup d'enfants.",
"Il vaut mieux perdre sa gow que _.",
"Ma bite sur ton front ça fait _.",
"_ #MDR c'est dar de ouf",
"Toi + moi = _",
"La personne à ma gauche est _.",
"Dans le monde des bisounours il y a _.",
"_ #il ne faut pas rêver non plus",
"Faire caca c'est _.",
"_ #pourquoi moi ?",
"L'avenir appartient à _.",
"J'aime jouir dans _.",
"Je préfère _ à _.",
"_ c'est un peu comme _ mais en plus hardcore !",
"_ #no pain no gain",
"Je n'ai jamais vu _ faire l'amour à quatre pattes.",
"_ #1.25/20 comme en latin",
"Dépuceler _, c'est forcément avec _ pour que ça soit mieux !",
"_ #haha mec je t'ai niqué",
"On a tous _ comme bouche-trou #au cas où x)",
"Empaler _, c'est vraiment dégueulasse !",
"Plutôt faire _ où aller en camping avec des potes ?",
"Touche pas à _ sinon j'te viole l'anus.",
"Le kebab du lendemain de soirée c'est _.",
"_ #lendemain de cuite",
"On la traine avec tendresse et délicatesse, _.",
"Papi aime bien _.",
"Papi aime bien _ quand mamie fait _.",
"Avec un gode géant on fait _.",
"Les racistes c'est comme _.",
"Les noirs c'est comme _.",
"Une fillette de 12 ans avec _ a déjà 9 enfants.",
"_ #à 6 ans c'est consentant",
"_ #in challah",
"La muscu avant _ !",
"Avaler _ ou _, franchement c'est presque la même chose !",
"_ #un trou c'est un trou ptin !",
"Regarder des séries c'est bien, _ c'est mieux !",
"_ #des grosses barres astrales",
"Sur un malentendu, _ ça peut passer.",
"Siroter _ c'est la vie man, le monde animal, prend le bien fort use _.",
"Le président et _ sont dans un bateau, le premier tombe à l'eau, il reste _.",
"Quand mon daron va _, ma daronne va _.",
"Mater des boobs sur Instagram quand on est aux chiottes c'est _.",
"Se torcher le cul avec _ ça fait mal !",
"Raconte-moi ton _.",
"Rien de tel que _.",
"Tout plaquer pour devenir _.",
"Si j'avais su _, je ne serais pas venu.",
"_ c'est quand même mieux que _ !",
"_ à un dîner de famille, ce n'est pas très convivial.",
"Mettre _ dans la cave, c'est la solution !",
"Ça fait 10 minutes qu'on se connait, je pense que _ est un peu prématuré.",
"_ m'est pas mal reproché dans ma vie de couple.",
"Ta grand-mère n'a pas aimé _, tu lui demanderas plus d'explications.",
"Je sais que si je t'épouse, j'épouse aussi _.",
"Pour une soirée de folie, il faut _.",
"Lors du premier rendez-vous, tu es venu avec _, je t'ai tout de suite reconnu !",
"On s'entend bien avec ma belle-mère, _ ne poserait pas de problème.",
"La musique, les pétales de rose sur le lit, les bougies, _, tout est prêt pour ce soir.",
"Quand je tombe sur _ sur Tinder, je like diiiiirect !",
"_ a fait hausser un sourcil à mon beau-père.",
"Faire mouiller la culotte de _ avec _, c'est simple.",
"J'ai toujours donné des petits nom à mes sextapes, celle-ci s'appelle _.",
"Vous allez me traiter de petite nature, mais _ il y a 1/4 d'heure, ça m'a coupé l'appétit.",
"Un truc à faire une fois dans sa vie c'est _, mais seulement une fois.",
"Alors ce week-end ? Bah comme d'hab : samedi _, et donc dimanche matin _.",
"Je n'ai jamais _, sauf une fois au chalet.",
"Jugé pour _, c'est la prison à vie assurée.",
"_ un métier d'avenir !",
"_ c'est quelque chose d'ordinaire.",
"Aujourd'hui, je me suis pignoler en pensant à _ !",
"J'ai aucun problème à reconnaître quand j'ai tord, mais _ c'est abusé.",
"_, ça fait vraiment du bien !",
"Manger au resto en chantant l'air de '_', chiche ou non ?",
"Se taper _ dès le matin #putain ça doit faire mal !",
"Prendre _ avec _, c'est le combo parfait !",
"On va tous _ jusqu'à la fin du monde, autant en profiter !",
"_ #gros juif de ses morts",
"_ #allez hop ça part au four !",
"Elle m'a dit _, je lui ai répondu _.",
"Il m'a dit _, je lui ai répondu _.",
"Plutôt _ ou _ ? Ballec de toute façon on va tous crever un jour !",
"Embrasser une personne avec beaucoup plus ou moins d'écart, c'est _.",
"Payer la tournée de _ au bar, c'est un concept à répandre.",
"_ #quoi de plus pour courroner le tout ?",
"_ en poster dans la pièce principale pour accueillir les invités, ça c'est classe !",
"_ à la bibliothèque #OKLM",
"Plutôt _ que _, bah oui forcément y'a pas moyen l'inverse !",
"_ après avoir bien bouffé #la PLS c'est tendu du string",
"_ ou _ ? Haaaaaaa le choix est difficile !",
"_ #t'inquiète mec j'arrive (MDRRRRR j'suis même pas encore parti !)",
"Avaler _ ou _, franchement c'est presque la même chose !",
"Insulter d'un _ ton pote quotidiennement, rien de plus normal ça veut dire que ça biche de ouf !",
"_ #et merde encore une soirée ou j'ai pas pécho...",
"J'ai vu _ sur un site de cul, franchement c'était grave dar !",
"_, c'est pas très halal !",
"_ est une bonne chose à faire tous les jours !",
"Mon patron m'a dit _ juste avant de me virer, la PLS !",
"_, ça fait très porno des années 80...",
"_, juste par pur plaisir.",
"Ne pas hésiter à _, c'est bon pour la santé !"
];

/**
 * Official list of the game, second edition.
 * I didn't include \n and I replaced '____' by '_'
 * 132 black cards.
 *
 * @type {string[]} the tab of official black cards.
 */
const BLACK_CARDS_LIST_BLANC_MANGER_COCO = [
"La vraie raison de mes premiers cheveux blancs, c'est _",
"Comparer _ et _, ce n'est rendre justice ni à l'un ni à l'autre",
"_ c'est bien, _ c'est mieux",
"_, un mal pour un bien",
"_ : le rêve, _ : la réalité",
"_, un travail bâclé",
"On a d'abord cru à un canular mais AQMI a bel et bien exigé _ pour la libération des 3 otages",
"_, c'est comme les mauvaises herbes : il faut traiter le problème à la racine",
"_ : Bien, _ : Pas bien",
"Quand une réunion client s'annonce mal, je ramène _, en général ça détend l'atmosphère",
"_ c'est un concept... On pourrait essayer",
"A quelques encablures du centre historique et loin de la cohue touristique, suivez le sentier côtier 5 minutes et venez admirer _",
"_ fait indéniablement partie de la culture française",
"_, j'y pense tous les matins en me rasant",
"Notre devis comprend aussi la livraison à votre domicile, un an d'assurance et _ pour le client fidèle que vous êtes",
"Malheureusement, avec votre apport initial, tout ce que notre banque peut vous proposer aujourd'hui c'est _",
"Ce qui distingue l'homme de l'animal à mon sens, c'est _",
"Mon dernier post Facebook est un selfie de moi avec _, j'ai eu 27 like",
"Bon... _, on l'a tous fait un jour ou l'autre",
//"Alors ce weekend ? Bah comme d'hab : vendredi soir _, samedi _ et donc dimanche matin _",
"J'ai 45 minutes de métro le matin pour aller au boulot, ça me laisse du temps pour _",
"Avant que je lise son testament, la dernière intention de votre père a été que je vous montre _",
"Ce qui m'a permis de résister toutes ces années en prison, c'est _",
"Un truc sympa, simple et romantique pour le soir de la Saint-Valentin, c'est _",
"Chez nous, _ se transmet de père en fils depuis des générations",
"Les belles histoires commencent toujours par _",
"_ : challenge accepted !",
"J'ai peut-être pas d'amis, pas de copine et pas de boulot, mais j'ai _",
"L'acuponcture n'a pas marché, l'hypnose non plus, alors ils ont tenté _",
"Pour me détendre le dimanche en fin d'après-midi, avant de reprendre le boulot, rien de tel que _",
"Pour moi les années 90 c'est avant tout _",
"Si t'es pas chaud tant pis, n'empêche que _ normalement ça ne se refuse pas",
"Papa, c'est quoi _ ?",
"_, c'est comme pour tout, il y a la théorie, et la pratique",
"_ a marqué à coup sûr le premier jour du reste de ma vie",
"Si tu plaides coupable pour _, tu peux t'en tirer avec _ ",
"_ poil au nez, _ poil au bras",
"_, c'est en quelque sorte ma madeleine de Proust",
"Oui ! Avec le Pack Sérénité votre logement est même assuré contre _",
"J'ai une technique simple pour réveiller en douceur un nouveau-né : _",
"_, pour moi, c'est une belle métaphore du quinquennat de François Hollande",
"Bon vent ! Mais fais attention à toi, _ est si vite arrivé",
"_, mes beaux-parents dominent allègrement le classement, et de loin",
"_, ça aurait dû se jouer à pile ou avatar-src",
"C'est quoi ton parfum ? _ de Guerlain",
"Père Noël, pour Noël je voudrais _",
"_, c'est la faute à pas de chance",
"La fin justifie _",
"Une GoPro c'est un peu gadget, mais c'est vrai que pour _, ça peut se justifier",
"Le péché mignon de Grand-Père, c'est _, c'est pour ça qu'on le trouve trop cool !",
"_, c'est le prix à payer pour la paix dans le monde",
"Vous allez me traiter de petite nature, mais _ il y a un quart d'heure ça m'a coupé l'appétit",
"Un truc à faire une fois dans sa vie, c'est _ ... Mais seulement une fois",
"_, La Mecque n'était peut-être pas l'endroit le plus indiqué, tu y avais pensé ?",
"Rater la naissance de son fils pour _, à la rigueur, ça peut se comprendre",
"_, YOLO",
"Je suis Monsieur Marc, vous notez : M comme une maison, A comme un Arbre, R comme Roméo, C comme _",
"Jusqu'à ce qu'elle évoque _, on passait presque un bon moment avec ma belle-mère",
"Le seul truc qui m'embête vraiment avec la mondialisation, c'est _",
"Afin d'apaiser les tensions interconfessionnelles dans le pays, le pape a prononcé un discours intitulé _",
"_ ne tue pas mais _ si",
"Le 8e jour, Dieu créa _ et il vit que cela était bon",
"_, c'est comme une bonne guerre, ça forge la jeunesse",
"_, ça c'est tellement ton père",
"Petit SMS pour vous souhaiter beaucoup de bonheur et _ pour cette nouvelle année",
//"Vous avez aimé _, vous aimez _, vous allez aimer _",
"Quand j'ai rencontré ta mère, ça a tout de suite été _",
"Mon investissement au Secours Catholique ? Je fais pas ça pour l'argent, je fais pas ça pour la gloire mais pour _",
"C'est quoi déjà ton truc qui marche bien contre les maux de gorge ? _", // Adding of _ at the end
"Contre toute attente, Martine et _ a été l'opus le moins vendu de la série",
"_ un problème, _ la solution",
"_ et _... Ou comment allier l'utile à l'agréable",
"Pour réussir _ il te manque _",
"Pour Grand Maître Jedi devenir, _ tu feras",
"Sans _, la fête est moins folle",
"J'aime le papier à bulle, l'odeur de la colle et _",
"Le sujet de ma thèse de doctorat, _, a été étonnamment mal reçu par le jury",
"Un tournevis, tu as ? Non. Alors passe-moi _",
"Amen, je vous le dis, celui qui croit en moi aura _",
"A 75 ans, il y a 2 choses que tu regrettes : _ et surtout _",
"J'ai toujours donné des petits noms à mes sextoys, celui-là s'appelle _",
"Aujourd'hui _, #VDM",
"_, c'est _",
"_, je ne nie pas les faits, je dis juste qu'ils sont exagérés",
"Plus que le mariage, ce qui a scellé notre union c'est _",
"Les premiers rayons de soleil, le pollen dans l'air, l'amour, _, le printemps quoi",
"Homme 45 ans, célibataire, bonne situation, cherche _",
"_, c'est le premier truc à larguer dans une montgolfière qui perd de l'altitude",
"_ : l'essayer c'est l'adopter",
"La gauche va pousser le thème du dialogue social, il faut absolument recentrer le débat sur _",
"Il y aura une baby-sitter pour le mariage ? Non mais on a quand même prévu, on a _", // Adding space before the ?
"C'est pas ce que je voulais dire, _, ce sont des propos sortis de leur contexte",
"C'est quoi ton mot de passe ? _ tout attaché ",
"_ : je m'en souviens pas. J'étais bourré",
"Au fond, ce qui manquait le plus à Auschwitz, c'était _",
"_ ça m'a pris 2 minutes et encore me suis pas pressé",
"Oui mon enfant, Dieu pardonne tout, même _",
"Pour le service réclamations, tapez 1, pour _, tapez 2, sinon veuillez patienter",
"Tu préfères _ ou bien _ ?",
"_ : le meilleur remède contre la gueule de bois",
"Petit on n'avait besoin de rien, on pouvait jouer une journée entière avec _",
"Afin de pimenter notre vie de couple après 35 ans de mariage, nous pratiquons _",
"800 g de viande hachée, 3 jaunes d'œufs, des câpres, de la sauce worcester et _ : là on tient un bon tartare",
"200 m² orienté plein sud, calme, haut standing, et le petit plus est à la cave : _",
"J'ai commencé _ quand j'avais 7 ans et demi, j'aurais peut-être dû attendre mes 9 ans",
"Tiens Roger, tu nous remettras _",
"En 3 je mets le travail, en 2 la famille et en 1 _",
"Pour égayer la vie d'un enfant aveugle, donne-lui _",
"Vous n'avez pas, M. Mitterrand, le monopole de _",
"Entre _ et une vie de famille, il faut choisir !",
"Promis, à partir du jour 1er janvier, j'arrête _",
"_, le film",
"_ ?? Avec ça, les videurs te laisseront jamais rentrer",
"A Abidjan, pour 1 euro tu peux avoir _",
"Si on se penche sur les statistiques, _ et _ sont étroitement corrélés",
"Le meilleur moyen aujourd'hui pour lutter contre la surnatalité en Afrique, c'est _",
"_, quand je te vois faire, je me dis que c'est un art",
"3 trucs qui remontent le moral et c'est physiologique, c'est le chocolat, le soleil et _",
"_, c'est tout le bonheur que je te souhaite, ma fille",
"Ça en a le gôut, ça en a la texture, la couleur, mais ce n'est pas _",
"_ : gros effort, petit résultat ; alors que _ : petit effort, gros résultat",
"_, c'est un détail à l'échelle de l'humanité",
"Si j'habitais en Californie, la chose qui me manquerait le plus de France, c'est _",
"_, ça n'existe pas, c'est des fables, des balivernes",
"Changer une vitre c'est comme _ : tu le feras aussi bien tout seul et ça te coûtera moins cher",
"_, c'est une luxe en période de crise",
"Il y a deux manières de sauver la France de la faillite, une grande réforme fiscale et _",
"Luc Besson se demande comment intégrer _ et _ à son adaptation de la vie de Saint-Paul",
"Un apéro sans pastis, et pourquoi pas _ sans _ tant qu'on y est ?",
//"Tu mets _, puis _, tu mélanges et abracadabra : _",
//"_ ça passe, _ ça passe encore aussi why not, mais _ là je dis stop",
"Le premier soir je me suis donc endormi sur le sable à mille milles de toute terre habitée. J'étais bien plus isolé qu'un naufragé sur un radeau au milieu de l'océan. Alors vous imaginez ma surprise, au lever du jour, quand une drôle de petite voix m'a réveillé. Elle disait : 'S'il vous plaît... dessine-moi _'"
];
