/**
 * List of white cards, each line must be into " " and finish by ','.
 *
 * @author GIRARD Timothée
 * @version 1.0
 */

/**
 * 209 white cards.
 *
 * @type {string[]} the tab of white cards.
 */
const WHITE_CARDS_LIST = [
"l'achever",
"un fils d'inceste handicapé",
"un fils de viol pas encore né",
"qui biche de ouf",
"la PLS astrale du seigneur zer",
"la misèrisation du string",
"dans mon anus dilaté",
"les petites qui squattent",
"faire l'amour à du fromage de chèvre.",
"un gâteau au foutre",
"un branle-gland",
"se dé-sousraciser",
"ma bite !",
"un shot Bailey-Chantilly",
"gouzi gouzi",
"ptin nique sa mère j'ai que des cartes pourries",
"le kamasutra",
"un résidu de sperme",
"dans les yaourts, dans les yaourts",
"se pignoler la nouille",
"jouir dans le corps d'un enfant mort",
"Matuidi Charo",
"demander de faire un dab à un amputé du bras",
"Jean-Michel branle-sperme",
"la fellation",
"une beurette de ses morts",
"un blaiiirrrrrr",
"la fragilité astrale",
"des meules énormes et sèches",
"une MILF toute ridée",
"faire du 170 km/h sur l'autoroute",
"Jaquie et Michel",
"pornhub",
"ma daronne",
"de la merde",
"faire un before",
"faire un after",
"la peau du pubis qui colle sur la vitre",
"débrancher mamie",
"un anus qui pète",
"un Arabe de ses mort",
"trouer la capote",
"un Jagerbomb bien corsé",
"la pilule du lendemain",
"un réfugié libanais",
"gagner des thunes",
"gagner 1000 balles à la roulette au casino",
"la levrette",
"mater Dragon Ball",
"un cul bien poilu",
"sauter dans l'eau à 20 mètres de haut",
"un bon boule bien ferme",
"un bébé mort-né",
"une poupée gonflable",
"le pape",
"un pédophile",
"un nécrophile",
"un handicapé mental",
"la personne à ma gauche",
"la gaule du seigneur",
"une bonne binouse bien fraîche",
"un cocktail à base de règles",
"la chatte de Nickita",
"chier en soirée quand tout le monde croit que tu vomis",
"boire cul sec un cimetière",
"vomir",
"un dindon",
"le fry chicken",
"2 pizzas pour 10 balles",
"un grec resté au frigo pendant 1 semaine",
"un ptit café zer",
"dormir sur une chaise bourré et tomber",
"la branlette du dimanche",
"mater des culs sur Instagram quand on est aux chiottes",
"sucer un orang-outan",
"devenir musclé en 1 jour",
"décuver en buvant encore plus",
"5 doigts dans le cul",
"2 doigts dans la chatte",
"toujours tout dramatiser",
"faire l'amour dans une botte de foin",
"une éjaculation précoce",
"un viol",
"la fécondation in vitro",
"taper sa bite contre la table en signe de protestation",
"avoir le sida",
"pomper sans discontinuer",
"le premier bisou avec la langue",
"le métissage",
"rester vierge jusqu'au mariage",
"Martine, 52 ans, caissière chez Auchan",
"pomper sans discontinuer",
"une sodomie",
"une faciale dégoulinante",
"le cancer du côlon",
"Janine, 67 ans, cougar",
"du GHB",
"l'haleine fétide du réveil",
"la bite dans le cul",
"une gode et du lubrifiant",
"des capotes et des menottes",
"une raclette",
"la syphilis",
"un petit africain",
"Robert, 59 ans, les aime jeunes, très jeunes",
"un gros bédo",
"ta soeur",
"une bonne fessée",
"mimer une pipe",
"paumer la clé des menottes",
"une blonde qui passait par là",
"une jeune fille de 12 ans",
"le regard plongeant vers son décolleté",
"le chantage a la sextape",
"une tournante dans une cave",
"une femme fontaine",
"une sextape à domicile",
"un transexuel",
"la pilule du lendemain",
"larguer par texto",
"le gras du bide",
"se faire gauler en matant un porno",
"faire son coming-out",
"débrancher mamie",
"un plot",
"les doigts qui collent",
"les filles de l'Est",
"jugé pour inceste à 93 ans",
"mater un porno gay en famille le dimanche soir",
"une péripapétitienne",
"l'inceste collectif",
"se faire pomper le dar",
"se masturber 3 fois par jour",
"un nazi",
"saupoudrer son repas d'hémoroïdes",
"un sorbet à base de caca de diahrée",
"c'est la crise astrale du seigneur zer qui biche pas de ouf",
"une bonne grosse sodomie",
"faire un before",
"faire un after",
"un cunilingus bien langoureux",
"monter sur le toit d'un batiment même si c'est interdit, juste pour le fun",
"saliver en voyant ta grand-mère à poil",
"un ptit asiat avec un gros pénis",
"un gros noir avec un ptit pénis",
"un plug anal",
"un vibromasseur connecté",
"ronfler comme jaja après une bonne grosse cuite sa mère la pute",
"s'endormit sur le trône la crotte au cul",
"un petit pet vaginal tout mignon",
"la baise",
"faire un gangbang attaché les uns aux autres",
"mourir du sida",
"boire du sperme en guise d'apéritif",
"aller au taf complètement rabat",
"aller à la messe pour gratter la tise et la quête",
"ramasser des gobelets consignés pour gratter de la thune",
"baiser une gow et la foutre enceinte car elle n'a pas pris la pilule (alors qu'elle l'avait dit la tchoin...)",
"commander un plat en anglais et se retrouver avec n'importe quoi dans l'assiette",
"s'endormir un verre à la main sans le renverser",
"mettre le cul ou la bite de ses potes en fond d'écran",
"dessiner une bite sur la bite de son pote",
"mito des compétences lors d'un entretien d'embauche",
"dans les toilettes publiques",
"couler un bronze qui pu l'oeuf pourri",
"chier un gros zder la porte ouverte",
"avec mes futurs gosses",
"inverser les cartes d'un joueur quand il est aux chiottes",
"sur mon bureau d'ordinateur",
"laisser trainer sa page porno en visioconférence professionnelle",
"sur une plage nudiste",
"mettre le son d'une vidéo porno à fond",
"dans un magasin d'électroménager",
"un POV dégoulinant",
"juifiser un clodo en PLS sur le trottoir",
"faire débander un mort",
"faire bander un âne",
"caissier à Leclert",
"se branler la nouille",
"avoir un gosse dont on ne connait rien",
"une quenelle titanesque",
"un camp d'extermination",
"un cam de feuj",
"une balle de fusil à pompe dans la tête",
"la bifle",
"du sale mamène",
"ce genre de joint",
"un anulingus",
"ce genre de bail mamène",
"ta grand-mère qui twerk",
"le ralouf",
"Didier, 43 ans, camionneur",
"Lisa, 21 ans, CAP coiffure avec un boule du turfu",
"la grosse bite du curé",
"les petites qui squattent",
"le balais à chiottes",
"la solution finale",
"sauter du 5ème étage",
"se faire juifiser",
"se faire exploser au milieu de la foule",
"crier 'ALLUAH AKBAR !!!'",
"#biais cognitif !",
"le confinement",
"le déconfinement",
"planche de sauciflard/fromage avec une bonne binouse",
"gratter un after chez les voisins du dessous",
"le Pitaya",
"la Tinderisation",
"le Covid19"
];

/**
 * Official list of the game, second edition.
 * I didn't include \n and I replaced '____' by '_'
 * 455 white cards, 12 empty (1 missing).
 *
 * @type {string[]} the tab of official white cards.
 */
const WHITE_CARDS_LIST_BLANC_MANGER_COCO = [
"Une faciale",
"La perte des eaux",
"30 ans de gonzo",
"Le gars qui crie POPOPOPOPOPOPO  POLOLO à Roland-Garros",
"La mauvaise foi",
"Voter utile",
"La gueule de bois",
"L'acharnement thérapeutique",
"La monogamie",
"Un noir, une pute, un belge et un homo",
"L'immunité parlementaire",
"La mentalité parisienne",
"Un 18 trous",
"Être VIP au Macumba",
"Traiter les femmes avec respect",
"Une petite pièce, une cigarette ou un ticket restaurant",
"Le Zyklon B",
"Un SMS qui dot qu'on arrive dans 15 minutes alors que pas du tout",
"Prendre l'hélico avec Balavoine et Florence Arthaud",
"Débrancher Mamie",
"un sorbet au foutre",
"Marcher pieds nus sur un lego",
"Enfiler sa burka",
"Un pyjama rayé avec étoile jaune",
"Le port du voile intégral",
"Soweto",
"En avoir plein le cul",
"Une platrée de choux de Bruxelles",
"L'huile de foie de morue",
"La quenelle",
"Vomir des spaghetti",
"Un pet humide juste ce qu'il faut",
"La droite décomplexée",
"Une crampe au poignet",
"Marcher pieds nus dans une salle de shoot",
"Le connard qui ne récure jamais les chiottes",
"Le chantage sexuel",
"Dire 'je t'aime' sans vraiment le penser",
"Les énarques",
"7 ans sans sexe",
"Magic System",
"Une bonne grosse teuf",
"La Renault Espace",
"Une fausse couche",
"Le quinquennat de François Hollande",
"Une maison avec jardin à Melun, une Opel Vectra et un labrador",
"Les francs-maçons",
"Pardonner à moitié",
"Une histoire d'amour avec un curé de 62 ans",
"Une pinte de glaire",
"Enculer les mouches",
"Une démocratie à l'africaine",
"Avoir une mi-molle",
"Une certification ISO 9001",
"Une promotion canapé",
"Un viol collectif",
"Europe Ecologie Les Verts",
"Un crédit conso",
"Les 'thaïlandaises'",
"Le point G",
"Un PSG/OM avec des pizzas et des bières",
"Prendre un enfant par la main",
"La sodomie pour les Nuls",
"Le savoir-être marseillais",
"Rater l'apéro",
"Un diabolo grenadine",
"Un boxer porté 8 jours de suite",
"Le minimum syndical",
"Le colonel Moutarde dans la cuisine",
"Être gardien au handball",
"Le subjonctif imparfait",
"Sniper la dernière famille de pandas sur Terre",
"Viser les pastilles de chlore bleues quand on pisse",
"Les années 80",
"Mes poignées d'amours",
"La Malaysia Airlines",
"Le petit Grégory",
"Monseigneur André Vingt-Trois",
"Être puceau à 40 ans",
"Faire une fausse promesse de don au Téléthon",
"La discrimination positive",
"Le Journal du hard",
"Marion Maréchal-Le Pen",
"Un costume 3 pièces Kiabi",
"Ma bite",
"Aménager un espace pour les roux",
"L'industrie de l'armement",
"Le traffic d'organes",
"Un déni de grossesse",
"Saga Africa, ambiance de la brousse",
"Le passage de la cocaïne au crack",
"Les boulettes de viande Ikea",
"Le coït",
"Une femme fontaine",
"La vague Bleu Marine",
"Prendre possession du podium",
"Refuser un test de paternité",
"Un poireau sur la joue",
"Work hard - Play - hard",
"Les fautes de goût",
"Fort Boyard",
"L'euthanasie systématique à 75 ans",
"Le troussage de domestique",
"La double pénétration",
"La gangrène généralisée",
"La grasse matinée",
"Les petites lèvres",
"Le botox",
"Le sperme qui colle sur la baignoire",
"Les juifs",
"Une poire à lavement",
"L'abstinence",
"Les pédés",
"Vouloir le meilleur pour son chien",
"L'Algérie française",
"La conduite en état d'ivresse",
"Guillaume Musso",
"Les femmes au volant",
"Céline Dion",
"Ebola",
"Les alcooliques dépressifs atteints de paralysie faciale",
"La langue de bois",
"Le problème de l'amiante dans le couloir de la mort",
"Les fausses résolutions du 31 décembre",
"Avoir une bouteille de Pétrus et pas de tire-bouchon",
"La propension naturelle des femmes à s'occuper des enfants et du foyer",
"Péter que le mec qui refuse de se lever de son strapontin",
"L'acné juvénile",
"Être une bête de sexe",
"La traditionnelle gaule matinale",
"Un poster Playboy au-dessus de mon lit",
"Francky Vincent",
"Voler les caisses de Médecins Sans Frontières",
"Une thèse sur les modèles prédictifs de la susceptibilité des cellules souches pluripotentes",
"Le rétablissement de la peine de mort",
"Commencer avec le doigt, finir avec le bras",
"Éjaculer après 47 secondes",
"Se triturer le gland",
"Le bonnet rouge du commandant Cousteau",
"L'adoption par les couples zoophiles",
"Éviter de manger trop gras, trop salé, trop sucré",
"Jouer au triangle dans un orchestre",
"Prendre le deuxième Big Mac à 1 euro",
"La pilule du lendemain",
"Faire l'amour et garder ses chaussettes",
"La Françafrique",
"Respecter les quotas",
"Les noirs",
"Une orgie de frères bénédictins",
"Lucy l'Australopithèque",
"Titiller la prostate",
"Un mâle reproducteur",
"La Macarena",
"La France d'en bas",
"La collaboration",
"www.impots.gouc.fr",
"Un pantalon coupé 'poutre-apparente'",
"Yabon Banania",
"Paumer son Alliance en teuf",
"L'Amicale des Anciens Khmers Rouges",
"Le passage du salaire brut au net",
"Aller voir chez les grecs si j'y suis",
"Un lieu pour se recueillir",
"Sortir du placard",
"Vivel Dop Fixation Béton",
"Se taper la nounou",
"1 mill&ard d'euro",
"Un cancer de la prostate",
"Le string qui dépasse",
"Rester sous la couette",
"Je t'aime, moi non plus",
"Mes vacances à St Barth'",
"La queue de chez Pôle Emploi",
"Un bout de salade coincé entre les dents",
"La réunionite",
"Kärcher à volonté",
"Un test de grossesse",
"Les filles de l'Est",
"Faire une croix sur les caresses et les préliminaires",
"Un frigo vide",
"Se torcher avec la Convention de Genève",
"La roulette russe",
"L'amant de ma femme",
"Une erreur de diagnostic au centre anti-VIH",
"Al Quaïda",
"Une grossesse prématurée",
"Le sexe punitif",
"Les envies de femme enceinte",
"Aller promener le chien",
"Mettre un aileron sur une Fiat Punto",
"Un zizi-oreille au petit matin",
"Mettre le feu à une garderie",
"Les bienfaits de la colonisation",
"Un dîner chez la belle famille",
"La ligue des éjaculateurs précoces",
"Le FN",
"Youporn comme page d'accueil",
"La ceinture de chasteté",
"Proposer un clope à un dauphin",
"Un CAP Coiffure",
"Les bonnes manières",
"Les caves de Sarcelles",
"Une raison de continuer à y croire",
"Pinailler sur le nombre de victimes de la Shoah",
"Les prêtres pédophiles",
"Battre sa femme",
"Le coup de grâce",
"Ma chatte bien sûr !!",
"Les fesses potelées",
"Rédiger des scripts pour mendiants",
"Amputer les mendiants pour qu'ils rapportent plus",
"Une lapidation en bonne et due forme",
"1 litre et demi de purin",
"Être en coloc avec Papa",
"Le racisme anti-blanc",
"Une AK-47",
"La traite des noirs",
"Tendre la joue gauche",
"Une crise hémorroïdaire",
"1 kg d'amiante",
"Une blague bien mysogine comme on les aime",
"Vladimir Poutine",
"Une blague raciste qui tombe au mauvais moment",
"Trois doigts dans le cul",
"Le best-of des chansons paillardes",
"Secouer la petite goutte",
"Annexer la Wallonie",
"Le sourire honnête et franc de mon banquier",
"Le dernier jour du condamné",
"Christine Boutin",
"Le Costa Concordia",
"Changer de femme pour monter en gamme",
"Ma Benz' volume max",
"Les punks à chien",
"La misère",
"Acheter une perruque",
"Un désaccord sur la notion de consentement",
"Avaler l'éthylotest",
"Dépuceler sans ménagement ni tendresse",
"Le vin en cubi",
"Les blancs",
"Une pipe au miel",
"Un sextoy pour chien",
"La paix dans le monde",
"Un couscous aux lardons",
"Dachau",
"Des menottes et un leg-in en latex",
"L'inspection des travaux finis",
"Réformer en France",
"Le droit de cuisage",
"Emile Louis",
"L'historique de mes 1000 dernières navigations internet, le vrai",
"La ménopause",
"Un conflit multipolarisé d'envergure internationale",
"L'odeur de la clope froide",
"Jouir ou mourir",
"Charrier un videur",
"La famille et les amis",
"Un pet de fouffe",
"Un cul pas plus large que ça",
"Ta Maman",
"Un ceintre à défaut de pilule abortive",
"Un Paki avec un bouquet de roses",
"Croire au Père Noël",
"Tirer la langue avant d'avaler",
"Flamby",
"Une pastille de Viagra",
"Serrer les fesses",
"Maubeuge",
"La sauce samouraï",
"Les arabes",
"72 vierges, comme promis",
"Coucher le premier soir",
"La purée blanche sous le prépuce",
"Aller aux putes",
"Trouver la fréquence des baby-phones du quartier",
"Du chocolat pour attirer les enfants",
"Une bonne vielle branlette",
"Les doigts qui collent",
"100 balles et un Mars",
"Enterrer une pute dans un désert",
"Blanc-Manger Coco",
"Un ver solitaire",
"Jacquie et Michel",
"Violer une chèvre",
"Un magret de canard/Nutella/cornichons/mascarpone",
"Un papillon tatoué dans le bas du dos",
"Louer un poney",
"Un chiotte à la turque et rien pour s'essuyer",
"Se faire gauler en matant un porno",
"Un samedi soir devant Le plus grand cabaret du monde",
"Le cassoulet William Saurin",
"Un canard en plastique jaune",
"Chier et pisser en même temps",
"La consanguinité",
"Les cotisations URSSAF et la CSG",
"La France de Vichy",
"Une perfusion de sang contaminée",
"Appeler un chat un chat",
"Égorger le mouton dans la baignoire",
"Allumer le feu",
"Le cannabis thérapeutique",
"Un bébé contre le sein de sa mère",
"Manger 5 fruits et légumes par jour",
"Les promesses électorales",
"Mettre de la moquette au mur",
"La mise en place d'une organisation tayloriste",
"Une gourmette en argent",
"Manger la couenne",
"Le plombier polonais",
"Marc Dutroux",
"Les activités extra-conjugales",
"Le concile Vatican 3",
"Parler la bouche pleine",
"Un coup de genou là où ça fait mal",
"La gastronomie allemande",
"Le slip kangourou",
"Bourrer les urnes",
"Bond, James Bond",
"Une banane pour Taubira",
"Les roms",
"Un œil pour un œil",
"Le grand théorème de Fermat",
"L'aide alimentaire pour la Somalie",
"Un rhube",
"Être en galère de PQ",
"Un concours de T-shirts mouillés",
"Ségolène, Valérie et Julie",
"Le droit à chacun de posséder une Rolex",
"Échanger des banalités",
"Le cumul des mandats",
"La levrette avec un chapeau de cowboy",
"Mettre Bébé dans la cave",
"La mort du petit Aylan",
"Les femmes qui font le poirier après l'amour",
"Acheter les alliances chez Tati Or",
"Des fleurs sur la tome de Pétain",
"L'intégrale de Katsuni",
"un plan-cul fiable",
"La morosité ambiante",
"Apprendre qu'on est cocu sur Closer",
"L'extrême onction",
"Perdre 1,2 kg quand on en pèse 123",
"Le verre de trop",
"Patrick Sébastien",
"La pétanque",
"Les rudiments de l'hygiène corporelle",
"Hiroshima",
"Faire croire qu'on est gay pour pouvoir toucher",
"Boire des bières et fumer des clopes",
"Faire un geste pour la planète",
"Chier vert",
"Le gras du bide",
"Sortir l'artillerie lourde",
"L'égalité homme-femme",
"La légitime défense",
"Dodo la Saumure",
"Le caca mou du lendemain de soirée",
"L'odeur du chemisier de Grand-Mère",
"Une chambre à l'heure",
"La culpabilité du lendemain",
"Candy Crush",
"Le Carlton de Lille",
"Un gros paquet",
"Un Tampax imbibé de Vodka",
"Envoyer 'Amour' au 8 200 200",
"Le concours national du lancer de nain",
"Deux doigts dans le cul",
"Un toucher rectal",
"Une pause gourmande",
"Payer pour voir des films porno en 2016",
"Un cercueil en kit",
"Quitter Neuilly",
"Les femmes",
"L'autotouchage",
"Relire Mein Kampf",
"21 cm de bonheur",
"Un bébé qui flotte dans un étang",
"Une bouteille de pastis et un Justin Bridou à partager",
"La tante à Robert",
"Larguer par texto",
"La charia",
"La République Démocratique du Congo",
"Aller aux prud'hommes",
"Un plan à trois",
"La gauche caviar",
"Un pitbull dans un jardin d'enfants",
"La franche camaraderie des tranchées",
"Le beurre et l'argent du beurre",
"Ouvrir un compte en Suisse",
"La sélection naturelle des espèces",
"Le caviar Beluga",
"Un doigt dans le cul",
"Les grands donateurs de la banque de sperme",
"Des chaussettes Mickey",
"Une place handicapé",
"Une fille qui fait plus que ses 15 ans",
"L'orgasme total",
"Jouer au docteur",
"un sandwich triangle sur une aire d'autoroute",
"Offrir une 8.6 à un SDF",
"Un abonnement à Famille Chrétienne",
"L'esprit Daech",
"Les populations métissées",
"Les problèmes de riches",
"10 astuces de grand-mère pour tomber enceinte",
"Faire la queue chez Burger King",
"Zlatan",
"100 ml de laxatif",
"une belle paire de nibards",
"Un sauna gay",
"Faire un trou dans sa poche pour se masturber en public",
"Des ladyboys séropositifs",
"Le gaz moutarde",
"Joseph Goebbels",
"Le génocide arménien",
"Ta sœur qui est aussi ta mère",
"3 petits pschitts de Febreze",
"La Gay Pride",
"Laisser 10 centimes de pourboire",
"L'envie de pisser",
"Une soutane et rien dessous",
"Une thérapie de couple",
"Embrasser la plus belle fille du lycée",
"Le tic-tac de l'horloge biologique",
"La beauf attitude",
"Passer une soirée en boîte en note de frais",
"Tenir la chandelle",
"La Manif Pour Tous",
"S'en foutre plein les fouilles",
"Les maximes de La Rochefoucault",
"Faire la une de FHM",
"Le remix techno de la BO de Pirates des Caraïbes",
"Investir dans une particule",
"Un Français bien de chez nous",
"Se curer le nez",
"Ce je-ne-sais-quoi des Ch'tis",
"Un Notre-Père et dix Je-vous-salut-Marie",
"Les habitants d'Évreux",
"La France",
"une vie de petit bourgeois",
"Une épisiotomie sans péridurale",
"Tirer une taffe après 6 mois sans clope",
"Licencier une mère célibataire",
"Une entorse au protocole",
"La première bière du vendredi soir",
"Les lourdeurs administratives",
"Une cuillère tordue, un briquet et une serringue",
"Une piqure de testostérone",
"Les machettes au Rwanda",
"La démobilisation des électeurs",
"Un Doliprane",
"Une étagère Billy",
"Les goudous",
"La jurisprudence de Nafissatou Diallo"
];