/**
 * List of expressions, each line must be into " " and finish by ','.
 *
 * @author GIRARD Timothée
 * @version 1.0
 */

/**
 * The expressions.
 *
 * @type {string[]} the tab of expressions.
 * @link https://www.narcity.com/vie/ca/qc/montreal/toutes-les-questions-que-tosera-jamais-poser-au-jeu-je-nai-jamais
 */
const EXPRESSION_LIST = [
// Les questions soft
//"Je n'ai jamais joué au jeu Je n'ai jamais.",
"Je n'ai jamais bu d'alcool.",
"Je ne me suis jamais saoulé avec mes parents.",
"Je n'ai jamais embrassé quelqu'un du sexe opposé.",
"Je n'ai jamais redoublé une année à l'école.",
"Je n'ai jamais eu de contravention.",
"Je n'ai jamais été malade à cause de l'alcool.",
"Je n'ai jamais menti à quelqu'un.",
"Je n'ai jamais foxé un cours au secondaire.",
"Je n'ai jamais fait de prank calls.",
"Je n'ai jamais embrassé une affiche d'une célébrité.",
"Je n'ai jamais mangé de la nourriture pour animaux.",
"Je n'ai jamais imité la signature de mes parents.",
"Je ne me suis jamais enregistré en train de chanter.",
"Je n'ai jamais lancé de nourriture sur la maison de quelqu'un.",
"Je n'ai jamais pleuré devant un film.",
"Je n'ai jamais dû reprendre mon examen de conduite.",
"Je n'ai jamais eu d'accident de voiture où j'étais fautif.",
"Je n'ai jamais mangé quelque chose qui était tombé par terre.",
"Je n'ai jamais embarqué dans la voiture d'un inconnu en faisant du pouce.",

// Les questions médium saignantes
"Je ne me suis jamais fait prendre par mes parents.",
"Je n'ai jamais envoyé de sextos.",
"Je n'ai jamais embrassé quelqu'un du même sexe.",
"Je n'ai jamais consommé de drogues.",
"Je n'ai jamais dit le mauvais nom pendant l'acte.",
"Je ne suis jamais sorti de chez moi sans sous-vêtement.",
"Je n'ai jamais eu de relations sexuelles avec une personne qui avait plus de 10 ans que moi.",
"Je n'ai jamais eu de relations sexuelles avec une personne qui avait moins de 5 ans que moi.",
"Je n'ai jamais couché avec la même personne qu'un de mes amis.",
"Je n'ai jamais faké d'avoir un orgasme.",
"Je n'ai jamais flirté avec une personne pour gagner un pari.",
"Je n'ai jamais flashé mes seins.",
"Je n'ai jamais envoyé de photos coquines.",
"Je n'ai jamais eu de relations sexuelles plus de 5 fois dans une journée.",
"Je ne me suis jamais masturbé plus de 5 fois en une journée.",
"Je n'ai jamais envoyé de sextos ou de photos coquines à la mauvaise personne.",
"Je n'ai jamais couché avec quelqu'un de mon job.",
"Je n'ai jamais fait l'amour ailleurs que dans un lit.",
"Je ne me suis jamais masturbé.",
"Je n'ai jamais couché avec quelqu'un ne parlant pas ma langue.",
"Je n'ai jamais fantasmé sur quelqu'un dans cette pièce.",
"Je n'ai jamais enfreins la loi.",

// Les questions rough
"Je n'ai jamais couché avec quelqu'un en couple.",
"Je n'ai jamais pensé coucher avec la/le partenaire d'un de mes amis.",
"Je n'ai jamais fréquenté plus d'une personne en même temps.",
"Je n'ai jamais eu un onenight non protégé.",
"Je ne me suis jamais fait arrêter par la police.",
"Je n'ai jamais essayé de jeux de rôles.",
"Je n'ai jamais espionné mes voisins.",
"Je n'ai jamais craché.",
"Je n'ai jamais fait l'amour dans une toilette publique.",
"Je n'ai jamais embrassé quelqu'un après avoir vomi.",
"Je n'ai jamais eu envie de tromper mon/ma partenaire.",
"Je n'ai jamais essayé de m'autosucer.",
"Je n'ai jamais eu plus de 20 conquêtes.",
"Je n'ai jamais eu de relations sexuelles avec un ex.",
"Je n'ai jamais essayé le sexe anal.",
"Je n'ai jamais pété en faisant l'amour.",
"Je n'ai jamais mangé de nourriture sur mon partenaire.",
"Je ne me suis jamais endormi pendant l'acte.",
"Je ne me suis jamais masturbé dans un lieu public.",
"Je n'ai jamais utilisé de jouets sexuels.",
"Je n'ai jamais eu d'ITS.",
"Je n'ai jamais été enceinte/faite tombé une femme enceinte.",
"Je n'ai jamais fantasmé sur une personne du même sexe.",
"Je n'ai jamais eu de relations sexuelles avec quelqu'un dans cette pièce.",
"Je n'ai jamais eu de relations sexuelles avec plus d'une personne dans cette pièce.",
"Je n'ai jamais menti aujourd'hui à ce jeu.",

// https://laviedesreines.com/questions/questions-je-nai-jamais/

// Questions rigolotes

"Je n'ai jamais conduit en étant bourré(e).",
"Je n'ai jamais espionné mon voisin.",
"Je n'ai jamais rien volé de cher.",
"Je n'ai jamais menti pour me sortir d'une situation embarrassante ou difficile.",
"Je ne me suis jamais fait virer d'un bar ou d'une discothèque.",
"Je n'ai jamais nagé nu(e) dans une piscine.",
"Je n'ai jamais pris de drogue ou fumé de l'herbe.",
"Je n'ai jamais rien transporté d'illégal.",
"Je n'ai jamais menti à mes parents sur l'endroit où j'étais.",
"Je ne me suis jamais fait arrêter.",
"Je n'ai jamais rien fait que j'ai regretté plus tard.",
"Je n'ai jamais fait semblant de connaître un parfait inconnu.",
"Je n'ai jamais chanté sous la douche.",
"Je n'ai jamais fait semblant de rire à une blague que je n'avais pas comprise.",
"Je n'ai jamais fait semblant d'être malade pour rester à la maison pour jouer aux jeux vidéos.",
"Je n'ai jamais rêvé de devenir une star de cinéma.",
"Je n'ai jamais regardé des dessins animés parce qu'ils me font rire.",
"Je n'ai jamais envoyé un message embarrassant à la mauvaise personne.",
"Je ne suis jamais tombé(e) en public.",
"Je ne me suis jamais fait pipi dessus.",
"Je n'ai jamais confondu un homme avec une femme, ou inversement.",
"Je n'ai jamais appelé la mauvaise personne pour ensuite prétendre que c'est à elle que je voulais parler.",
"Je ne me suis jamais enregistré(e) en train de danser ou chanter.",
"Je n'ai jamais crié à cause d'un moustique.",
"Je n'ai jamais menti au cours de ce jeu.",

// Questions embarrassantes

"Je n'ai jamais dit “je t'aime” juste pour coucher avec quelqu'un.",
"Je n'ai jamais expérimenter pour découvrir mon orientation sexuelle.",
"Je n'ai jamais espionné un(e) ex sur les réseaux sociaux.",
"Je ne suis jamais tombé(e) amoureux(se) de quelqu'un que je connaissais seulement par le biais des réseaux sociaux.",
"Je n'ai jamais embrassé mon ou ma meilleur(e) ami(e).",
"Je n'ai jamais embrassé quelqu'un sans savoir qui c'était.",
"Je n'ai jamais été amoureux(se) d'un(e) de mes professeur(e)s.",
"Je n'ai jamais été amoureux(se) de la petite amie (ou du petit ami) de mon frère (ou de ma soeur).",
"Je n'ai jamais été à un RDV galant sans savoir qui j'allais rencontrer.",
"Je n'ai jamais flirté avec quelqu'un qui avait 10 ans de plus que moi.",
"Je ne suis jamais sorti(e) avec plus d'une personne à la fois.",
"Je n'ai jamais été dans un sex shop.",
"Je n'ai jamais eu un fantasme à propos d'un(e) de mes ami(e)s.",
"Je n'ai jamais couché avec l'ex de mon/ma meilleur(e) ami(e).",
"Je n'ai jamais fait un tatouage que je regrette maintenant.",
"Je n'ai jamais fait un striptease qui a mal tourné.",
"Je n'ai jamais posé un lapin à mon/ma petit(e) ami(e).",
"Je n'ai jamais regardé quelqu'un faire l'amour.",
"Je n'ai jamais mesuré mon sexe ou celui de mon partenaire.",
"Je n'ai jamais fait semblant d'aimer le sexe.",
"Je n'ai jamais laissé quelqu'un me regarder pendant que je faisais l'amour.",
"Je n'ai jamais fait semblant d'aimer le sexe oral.",
"Je n'ai jamais fait l'amour sans prendre de douche avant.",
"Je n'ai jamais fait l'amour.",
"Je n'ai jamais ressenti un orgasme.",

// Questions générales et personnelles

"Je ne me suis jamais vanté d'une chose que je n'avais pas faite.",
"Je ne me suis jamais moqué(e) de quelqu'un.",
"Je n'ai jamais regardé les Anges de la télé-réalité.",
"Je n'ai jamais parié sur quelque chose.",
"Je ne suis jamais sorti(e) de chez moi sans sous-vêtements.",
"Je n'ai jamais consommé de drogues.",
"Je n'ai jamais flirté avec quelqu'un pour gagner un pari.",
"Je n'ai jamais enfreint la loi.",
"Je n'ai jamais eu d'accident de voiture par ma faute.",
"Je n'ai jamais pleuré devant un film.",
"Je n'ai jamais bu d'alcool.",
"Je ne me suis jamais saoulé avec mes parents.",
"Je n'ai jamais bavé dans mon sommeil.",
"Je n'ai jamais eu le coeur brisé.",
"Je n'ai jamais appelé mon partenaire par le prénom d'un(e) de mes ex.",
"Je n'ai jamais surpris quelqu'un en train de regarder des films pornographiques au travail.",
"Je n'ai jamais volé le mot de passe de mon/ma partenaire.",
"Je n'ai jamais fréquenté plus d'une personne en même temps.",
"Je n'ai jamais eu envie d'être infidèle.",
"Je n'ai jamais couché avec un(e) collègue de travail.",
"Je n'ai jamais obtenu un poste de travail grâce au sexe.",
"Je n'ai jamais participé à un double RDV seulement pour que mon ami(e) puisse sortir avec la personne pour qui il ou elle avait le béguin.",
"Je n'ai jamais menti pendant un RDV galant afin d'y mettre un terme au plus vite.",
"Je n'ai jamais tellement bu que je me suis endormi(e) pendant l'acte.",
"Je n'ai jamais menti pour cacher l'infidélité de mon/ma meilleur(e) amie.",

// Questions coquines

"Je n'ai jamais eu une relation ouverte.",
"Je n'ai jamais été infidèle.",
"Je n'ai jamais pris des photos coquines pour les envoyer à un(e) ex.",
"Je n'ai jamais eu une relation d'un soir.",
"Je n'ai jamais embrassé quelqu'un du même sexe.",
"Je n'ai jamais acheté de la lingerie SM.",
"Je n'ai jamais regardé de films pornographiques.",
"Je n'ai jamais joué au strip-poker.",
"Je n'ai jamais fait l'amour dans un lieu public.",
"Je n'ai jamais fait de vidéo coquine.",
"Je n'ai jamais été menotté.",
"Je n'ai jamais fait l'amour avec les yeux bandés.",
"Je n'ai jamais fait semblant d'avoir un orgasme.",
"Je n'ai jamais fait semblant d'aimer le missionnaire.",
"Je n'ai jamais pratiqué la cowgirl inversée.",
"Je n'ai jamais participé à une partie à trois.",
"Je n'ai jamais regardé mon/ma partenaire se mastruber.",
"Je ne me suis jamais fait surprendre par un membre de ma famille.",
"Je n'ai jamais envoyé de sextos.",
"Je n'ai jamais couché avec la même personne que mon frère ou ma soeur.",
"Je n'ai jamais envoyé de photos coquines à la mauvaise personne.",
"Je ne me suis jamais masturbé(e) plus de trois fois dans la même journée.",
"Je n'ai jamais fait l'amour ailleurs que dans un lit.",
"Je n'ai jamais couché avec une personne dont je ne comprenais pas la langue.",
"Je n'ai jamais couché avec quelqu'un qui était déjà en couple."
];